// ============================================================================
// CLAIM CLOSURE — when a file stops being open, as distinct from when it is paid.
//
// Money leaves before files close, and the two curves are INDEPENDENT. WC pays
// 41% of a cohort in its first year and closes 49% of its claims; GL pays 10%
// and closes 27%. Deriving one from the other would collapse a real distinction:
// a closed claim has paid everything it will ever pay, an open one has not, and
// the share of a cohort's dollars that has left is not the share of its files
// that are finished. So this module never reads payoutPattern.ts and
// payoutPattern.ts never reads this one.
//
// SAME FORM AS THE PAYOUT PATTERNS, for the same reason — a curve with recorded
// parameters rather than a table, so a valuation at any age is defined and no
// interpolation rule has to be invented:
//
//     closedShare(t) = 1 - exp(-(t/b)^k)
//
// where t is YEARS SINCE THE ACCIDENT YEAR, on the same convention
// payoutPattern.ts uses: a cohort at `age = a` sits at curve age a + 1.
//
// ⚠ FITTED AGAINST REAL POOL EXPERIENCE, EACH LINE SEPARATELY, AND THE SOURCE
// DATA IS NOT IN THIS REPO. The parameters ARE the record — the same discipline
// FITTED_PAYOUT_PATTERN carries, and the same reason: the shape came from the
// pool's own closure experience and the fit is what survives, not the triangle
// it was fitted against.
// ============================================================================

export interface ClosureCurve {
  /** Shape. k < 1 closes fast then crawls; k > 1 defers then accelerates. */
  k: number;
  /** Scale, in years. */
  b: number;
}

/** Share of an accident year's claims closed by curve age `t` (years). */
export function closedShare(c: ClosureCurve, t: number): number {
  if (t <= 0) return 0;
  return 1 - Math.exp(-Math.pow(t / c.b, c.k));
}

// ============================================================================
// A CLAIM'S OWN CLOSURE DRAW — deterministic, storage-free, monotone, AND
// INDEPENDENT ACROSS GAMES.
//
// ⚠ IT HAS TO BE DERIVED RATHER THAN STORED. Ruling 8 keeps the claim register
// out of persistence: `LineResultSet.claims` is in-memory only and, when a save
// has dropped it, is regenerated by claimRegeneration.ts from the roster and
// scalars the result carries — exactly, ids included, as save-round-trip-check
// asserts. (For most of this project that sentence described nothing; it does
// now.) So a claim's status
// cannot be accumulated state — it has to be a pure function of what the claim
// already carries.
//
// Each claim gets one uniform, fixed for its life. It is closed at curve age t
// exactly when the closure share has reached that uniform. Because the share is
// monotone increasing in t and the uniform never moves, a claim closed at one
// valuation is closed at every later one — closure cannot un-happen, which a
// per-valuation draw would allow.
//
// ⚠ THE GAME IDENTITY IS AN INPUT, AND ITS ABSENCE WAS A DEFECT. Claim ids carry
// no seed — `wc-1-member-004-large-0` is the same string in every game — so
// hashing the id alone gave the same closure unit to the same SLOT in every
// game. Measured across two games with unrelated seeds: 21.9% of WC claim ids
// collided (GL 2.8%, Property 12.9%), and NONE of the collisions carried the
// same claim amount. A closure-driven developing set would then evolve partly
// independently of the seed, which is exactly what
// enrolment-independence-check exists to prevent elsewhere.
//
// ⚠ THE SEED GOES IN THE HASH, NOT IN THE ID, and that is the cheaper of two
// correct fixes. Claim ids are join keys — the claims workbook joins them to
// occurrence development, and the development ledger keys off them — so changing
// their SHAPE has reach into every consumer. Hashing (gameId, claimId) buys the
// same independence and touches nothing that joins. In the app the numeric seed
// is `seedFromInstanceId(instanceId)`, a pure function of the instance id, so
// the two carry identical information and the id is the one already threaded to
// every call site that needs it.
//
// ⚠ AND THE HASH NEEDS ITS FINALISER. This was plain FNV-1a returning the TOP 24
// bits, and FNV's last multiply leaves the high bits poorly diffused on short
// structured keys. Measured mean unit: WC 0.4882 against 0.5000, chi-squared(9)
// of 258 against a 21.7 critical value, biasing WC's age-1 closure +1.75 points.
// GL read clean at 0.4994 — its ids are fixed-shape and end `-c1`, while WC's
// end in a variable-length component token and run 23-32 characters. A hash that
// is uniform on the line you happen to test first is the failure mode here, so
// closure-draw-check asserts uniformity PER LINE.
//
// FNV-1a plus an xorshift-multiply avalanche, and deliberately NOT the project's
// SeededRandom: this is not a simulation draw and must not touch any RNG stream.
// Consuming from a seeded stream would move every downstream draw and re-roll
// the game, for a quantity that is a read-time property of a claim that already
// exists.
// ============================================================================
export function claimClosureUnit(gameId: string, claimId: string): number {
  let h = 2166136261 >>> 0;
  // The game identity first, separated by a byte that cannot occur in either
  // string, so (gameId, claimId) can never be confused with a different split of
  // the same concatenation.
  for (let i = 0; i < gameId.length; i++) {
    h ^= gameId.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  h ^= 0x1f;
  h = Math.imul(h, 16777619) >>> 0;
  for (let i = 0; i < claimId.length; i++) {
    h ^= claimId.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  // The avalanche. Without it the top bits carry the bias measured above.
  h ^= h >>> 16;
  h = Math.imul(h, 2246822507) >>> 0;
  h ^= h >>> 13;
  h = Math.imul(h, 3266489909) >>> 0;
  h ^= h >>> 16;
  return (h >>> 8) / 16777216;
}

/**
 * Is this claim closed as at curve age `t`?
 * `curve` is the claim's own — see resolveClosureCurve for the size split.
 */
export function isClaimClosed(curve: ClosureCurve, gameId: string, claimId: string, t: number): boolean {
  return closedShare(curve, t) >= claimClosureUnit(gameId, claimId);
}

// ============================================================================
// THE PER-CLAIM PAYMENT SPLIT — A SPLIT, NEVER A SCHEDULE.
//
// ⚠ NO CLAIM EVER DRAWS ITS OWN PAYMENT SCHEDULE, and this is the load-bearing
// prohibition of the whole paid ledger. Read the reason before changing anything
// here, because the failure it prevents is invisible from this file.
//
// The engine develops the RESERVE, not the ultimate:
//
//     newUnpaid = (netUnpaid - paydown) x factor
//
// so the cohort's paydown TOTAL sets the base that development multiplies. Pay
// more this year and the same factor moves fewer dollars; development shrinks,
// and cession shrinks with it. Payment allocation is cession-neutral ONLY
// because the payout pattern fixes that total before any split happens.
//
// cedeDevelopment reads `c.current` and the deltas and nothing else, so payment
// cannot reach the cession function directly. The danger is entirely indirect
// and entirely through the total. Give a claim its own payment curve and the
// cohort total stops being the pattern's, the development base moves, and the
// free-lunch surface reopens somewhere nothing is watching.
//
// So: the dollars come from the cohort's own gross paydown, which the pattern
// already set, and this function only decides WHO GETS THEM.
// paid-ledger-check.ts asserts the sum to the cent at every valuation.
//
// ============================================================================
// ⚠ THE SPLIT IS A PROPERTY OF THE REGISTER, NOT OF A CLAIM, AND THAT IS WHY
// THIS TAKES THE WHOLE COHORT.
//
// It used to be `claimPaidWeight(claimGrossUltimate, registerGrossSum)` — pro
// rata by gross ultimate, computable one claim at a time, and knowing nothing
// about closure. That gave EVERY OPEN CLAIM THE COHORT'S AVERAGE PAID SHARE,
// which is incoherent on its own terms: the workbook printed GL claims that were
// open and 99.8% paid, and a GL claim open at age 5 was booked 94.7% paid. A
// file that has paid 94.7% of itself and is still open is not a claim any
// adjuster would recognise.
//
// It is also load-bearing for what comes next. A per-claim revision law floored
// at paid-to-date cannot go below what has already been paid, so with headroom
// that thin the floor binds on essentially every large open claim and the
// truncation injects a systematic UPWARD drift — measured at +18.8% of the
// cohort ultimate on WC, +6.7% on GL, +2.3% on Property. That is not a rounding
// error; WC's is three quarters of the line's whole development SD. And "a claim
// closes at zero", which real settlement data shows for 19% of claims, is
// arithmetically impossible for a file already booked 94.7% paid.
//
// ============================================================================
// THE RULE, AND IT IS TWO TIERS RATHER THAN A WEIGHTING.
//
//   1. A CLOSED CLAIM HAS PAID EVERYTHING IT WILL EVER PAY.  Its paid is its own
//      gross ultimate. This is a DEFINITION, not a curve — see the boundary note
//      below, because it is the whole of what this file borrows from closure.
//   2. THE OPEN CLAIMS SHARE WHAT IS LEFT, pro rata by gross ultimate — the old
//      rule exactly, applied to the residual instead of to the whole.
//
// If the cohort has not paid enough to settle even its closed files, tier 1 is
// scaled down pro rata and the open claims get nothing; they then carry 100%
// headroom, which is the right answer rather than a degenerate one.
//
// ⚠ WHY THIS NEEDS NO ITERATION, AND THE ONE CASE WHERE THE CAP STILL BREAKS.
//
// The open tier's residual is `cohortGrossPaid - closedTotal`. WHILE THE COHORT
// HAS PAID NO MORE THAN ITS REGISTER SUMS TO, that residual is at most
// `registerGrossSum - closedTotal`, which IS the open total, so the open tier's
// scale factor cannot exceed one and no claim can pass its own ultimate. A
// general cap-respecting waterfall would iterate; under that condition this one
// provably finishes in two passes, so it does not.
//
// THE CONDITION IS NOT GUARANTEED. `registerGrossSum` is frozen at inception and
// the cohort's gross ultimate DEVELOPS above it, so an adversely developed
// cohort late in its runoff can have paid more than its register sums to. The
// scale factor then exceeds one and the open claims are booked above their drawn
// ultimates.
//
// THAT IS PRE-EXISTING AND IT IS NOT MADE WORSE HERE. The old pro-rata rule did
// the same thing to every claim in the cohort at once, for the same reason. It
// is not fixed in this commit because the fix is not a payment rule: the drawn
// value is stale, and Stage 1's per-claim revision is what makes a claim's
// carried value track its cohort. paid-headroom-check MEASURES the frequency
// rather than asserting it away, and the number is in its output.
//
// ⚠ THE TIE WINS OVER THE CAP where the two conflict. Clamping the open tier
// would silently drop dollars and break "the split sums to the cohort's paydown
// to the cent", which is the invariant the whole paid ledger rests on. A visible
// paid-over-incurred on a developed cohort is a worse-looking, better-behaved
// answer than a ledger that does not add up.
//
// ============================================================================
// ⚠ THE NAIVE REWEIGHT WAS TRIED AND IT FAILS. DO NOT RETRY IT.
//
// The obvious fix is to weight each claim by how far it is through its own
// closure — `w_i = v_i x progress_i`, normalised over the register, where
// progress is `closedShare(t) / u_i` against the claim's own closure unit. It is
// one line and it is worse than what it replaces. MEASURED: it left 78.2% of
// open WC claims at ZERO headroom at age 1, against 0.0% under the old pro-rata
// rule.
//
// The reason is the normaliser. A closed claim is capped at its own ultimate and
// cannot absorb more, but a normaliser that only sees weights does not know
// that, so the dollars a closed claim cannot take are handed to open claims
// instead of being withheld — the allocation OVER-pays exactly the files that
// most need headroom. Any scheme that normalises weights without enforcing the
// cap has this defect regardless of the weight's shape, which is why the fix is
// a tiered allocation and not a better weight.
//
// ============================================================================
// ⚠ THE BOUNDARY WITH THE CLOSURE CURVE, WHICH THIS FILE'S OWN HEADER POLICES.
//
// The header above says the two curves are independent and that "reusing a
// closure curve as a payment curve is exactly the collapse the header of this
// file refuses". That prohibition stands and this does not breach it, but the
// line is fine enough to be worth drawing exactly:
//
//   WHAT IS REFUSED: deriving how much a claim has PAID from how far through
//   CLOSURE it is. A progress-shaped payment curve — tier 2 weighted by
//   progress rather than flat — would be that, and it is not done here. There is
//   still no fitted per-claim payment curve, by size or by progress, and when
//   one exists tier 2's flat pro rata is where it goes.
//
//   WHAT IS USED: the BINARY closed/open state, and only through the definition
//   that a closed file has finished paying. No shape, no rate, no schedule.
//
// THE COST IS REAL AND IS ACCEPTED: the Paid column now moves when the closure
// parameters move, which it did not before. That coupling is new, it is named
// here so it is not discovered later, and it buys coherence between two columns
// that previously contradicted each other on the same row.
//
// ⚠ AND THE TOTAL IS UNTOUCHED, which is the only thing cession-neutrality ever
// depended on. `cohortGrossPaid` is the pattern's, this function never computes
// it, and the split still ties to the cent. Nothing in the loss path reads any
// of this — the only consumers are the claims workbook and paid-ledger-check.
//
// ============================================================================
// ⚠ THIS DOES NOT MAKE A PAID-TO-DATE FLOOR SAFE, AND MUST NOT BE READ AS
// HAVING DONE SO. MEASURED, in paid-headroom-check's own output:
//
//   truncation drift on the cohort ultimate    OLD split -> NEW split
//     WC        55.4% -> 42.5%      GL  21.0% -> 15.3%     Property 9.2% -> 4.5%
//   (at the revision law's ruled scale; the fall is 23-51% and it is real)
//
// Against a martingale tolerance of about 1% of booked ultimate, 42.5% is not a
// near miss. The reason is structural rather than a residual defect in the
// allocation: at the ruled scale a large claim's annual revision SD is around
// 50% of its own value, which is the same order as the headroom ANY coherent
// payment schedule can leave on a file that has been paying for years. No split
// closes that gap, so the choice at Stage 1 is between grading this tier-2 pro
// rata by closure progress — which is the payment-curve collapse the boundary
// note above refuses, and would need a fit that does not exist — or revising the
// CASE RESERVE rather than the incurred, which has no floor and keeps the
// martingale by construction. That is a ruling, not a code change, and it is
// open.
//
// What this commit does buy is real and is the precondition either way: the
// columns stop contradicting each other, "closes at zero" becomes arithmetically
// possible, and the drift that remains is a smaller number to argue about.
// ============================================================================

/** One register entry, as the split needs to see it. */
export interface PaidSplitClaim {
  /** The claim's own gross ultimate. */
  grossUltimate: number;
  /** Closed as at the valuation being struck — `isClaimClosed` at that same age. */
  closed: boolean;
}

/**
 * Split a cohort's cumulative gross paid across its register.
 *
 * Returns dollars per claim, in the order given, summing to `cohortGrossPaid`
 * (to float precision) whenever the register is non-empty and carries value.
 *
 * ⚠ RETURNS DOLLARS RATHER THAN WEIGHTS, deliberately. The tier boundary depends
 * on how the paid total compares with the closed total, so a "weight" here would
 * be a function of the dollars it was about to be multiplied by — a weight in
 * name only. Callers wanting shares divide by the total themselves.
 */
export function claimPaidSplit(
  claims: readonly PaidSplitClaim[],
  cohortGrossPaid: number,
): number[] {
  const out = new Array<number>(claims.length).fill(0);
  if (!(cohortGrossPaid > 0) || claims.length === 0) return out;

  let closedTotal = 0;
  let openTotal = 0;
  for (const c of claims) {
    const v = Math.max(0, c.grossUltimate);
    if (c.closed) closedTotal += v; else openTotal += v;
  }
  if (closedTotal + openTotal <= 0) return out;

  if (cohortGrossPaid <= closedTotal) {
    // Short of settling even the closed files: scale tier 1, open claims wait.
    const f = cohortGrossPaid / closedTotal;
    claims.forEach((c, i) => { if (c.closed) out[i] = Math.max(0, c.grossUltimate) * f; });
    return out;
  }

  const residual = cohortGrossPaid - closedTotal;
  const f = openTotal > 0 ? residual / openTotal : 0;
  claims.forEach((c, i) => {
    const v = Math.max(0, c.grossUltimate);
    out[i] = c.closed ? v : v * f;
  });

  // ⚠ THE REMAINDER WHEN NO OPEN CLAIM IS LEFT TO TAKE IT. A fully closed
  // register whose cohort has paid more than the register sums to — an adversely
  // developed cohort, see the cap note above — would otherwise drop those
  // dollars and break the tie. They go back onto the closed files pro rata,
  // which is where a developed cohort's extra payments belong. Without this the
  // split silently stops summing to the cohort's paydown on exactly the oldest
  // accident years, which is where nobody re-checks it.
  if (openTotal <= 0 && residual > 0 && closedTotal > 0) {
    claims.forEach((c, i) => {
      if (c.closed) out[i] += Math.max(0, c.grossUltimate) * (residual / closedTotal);
    });
  }
  return out;
}
